package classes.Scenes.Monsters 
{
	import classes.BaseContent;
	import classes.GlobalFlags.kFLAGS;

	public class DemonSoldierScene extends BaseContent
	{
		
		public function DemonSoldierScene() 
		{
			//Nothing to declare here.
		}
		
		public function encounterTheSoldierz():void {
			clearOutput();
			credits.modContent = true;
			credits.authorText = "Doc_Vermin";
			monster = new DemonSoldier();
			if (flags[kFLAGS.DEMON_SOLDIERS_ENCOUNTERED] < 1) {
				outputText("As you pick your way through the terrain a shadow passes overhead, looking up you spot a large flying shape silhouetted against the sun. At first you think it might be some sort of bird, but as the shape swoops closer you see that the wings are more like those of a bat, with a long, spaded tail trailing out behind. Uh-oh...");
				outputText("\n\nThe Demon lands in front of you with an almost liquid grace. " + monster.mf("He", "She") + " folds " + monster.mf("his", "her") + " wings behind " + monster.mf("his", "her") + " back, and " + monster.mf("his", "her") + " tail whips back and forth as a truly malevolent grin splits the infernal creature's face.");
				if (player.demonScore() < 4) outputText("<i>\"Well well, it looks like I've found some sport to liven up a dull patrol!\"</i>");
				else outputText("\"<i>Hmm... you may look like one of us, but I can smell your soul from here; I shall enjoy fucking it out of you!\"</i>");
				outputText(" The " + (monster as DemonSoldier).demonTitle(0) + " purrs. \n\nThe demon draws " + monster.mf("his", "her") + " wickedly serrated scimitar and adopts an aggressive combat stance. It's a fight!");
				flags[kFLAGS.DEMON_SOLDIERS_ENCOUNTERED] = 1;
			}
			else {
				outputText("Another of Lethice's demonic soldiers swoops down out of the sky and attacks, announcing \"<i>I'll enjoy turning you into a fuck-toy, mortal!\"</i>");
				outputText("\n\nThis time, the demon is " + (monster as DemonSoldier).demonTitle(1) + " and " + monster.mf("he", "she") + " draws " + monster.mf("his", "her") + " scimitar. It's a fight!");
				flags[kFLAGS.DEMON_SOLDIERS_ENCOUNTERED]++;
			}
			startCombat(monster);
		}
		
		public function victoryOverSoldier(hpVictory:Boolean):void {
			clearOutput();
			if (hpVictory) {
				outputText("The " + (monster as DemonSoldier).demonTitle() + " sprawls on ground before you, weakened and dazed, you're quite sure {he/she} couldn’t put up even the slightest resistance to anything you might want to do...");
			}
			else {
				outputText("The " + (monster as DemonSoldier).demonTitle() + " can take no more of your relentless sexual stimulation, and gasps as {he/she} drops to {his/her} knees, frantically masturbating with both of {his/her} hands <i>and</i> {his/her} tail. <i>\"Unngh... Holy Mother of Fuck, Ahh... what manner of mortal [b]are[/b] you?\"</i>");
			}
			outputText("\n\n<b>What (if anything) do you want to do to the Demon Soldier, and with what part of your body?</b>");
			menu();
			//Victory fuck goes here.
			if (player.lust >= 33) {
				addButton(0, "Get Oral", giveTheDemonGoodFacial).hint("Put the demon's mouth to a good use servicing you.");
				//addButton(1, "Fuck Vag", giveTheDemonVagFuck).hint("Put that cock of yours to a good use breeding the demon."); //Sadly no written scene. Same with anal.
			}
			//Eliminate the demon threat.
			if (hpVictory) addButton(3, "Kill " + monster.mf("Him", "Her"), killTheSoldier);
			else addButtonDisabled(3, "Kill " + monster.mf("Him", "Her"), "You must have beaten the demon by reducing " + monster.mf("his", "her") + " HP to zero.");
			//Nothing? Fuck off kindly.
			addButton(4, "Leave", getGame().combat.cleanupAfterCombat);
		}
		
		private function giveTheDemonGoodFacial():void {
			clearOutput();
			//TODO: Make this fully functional and dynamic.
			/*outputText("You approach the vanquished " + (monster as DemonSoldier).demonTitle() + " " + (player.cor < 40 ? "hesitantly" : (player.cor < 75 ? "with a wicked grin on your face" : "positively salivating at the prospect of raping {him / her} senseless")) + ", and quickly set about stripping both yourself and your victim naked.");
			outputText("\n\nTaking the belt from the Demon's scabbard, you bind {his/her} hands behind {him/her} (making sure to trap {his/her} wings as you do so), and roll the creature over onto {his/her} back, then stand back to look over your helpless victim.");
			outputText("\n\nThe " + (monster as DemonSoldier).demonTitle() + " squirms and moans on the ground as you squat down beside {him/her} and slowly run your finger-tip around {his/her} [is(ehasPenis = true) " cock head "][if(ehasPenis = false) " pussy lips "] before leisurely drawing {him/her} up the infernal beast's midriff, over {his/her} [chest] and up to {his/her} lips, where the Demon begins to suckle enthusiastically at the intruding digit.");
			outputText("\n\nYou decide to take advantage of the hellish monster's willing mouth.");
			outputText("\n\n[if(hasPenis = true) " Putting the head of your [cock biggest] to the creature's soft, glossy lips, the fiend again begins to suckle, and [eachCock] begin[if(cocks = 1) "s " ] to swell. Soon your throbbing fuck-stick [if(cocks > 1) "s are "][if(cocks = 1) " is "] granite-hard.");
			outputText("\n\n[if(cockSmallest =< 65) " Grabbing hold of the Demon's horns you ram your [cockFit 65] deep into {his/her} gullet, the beast easily takes your meaty dick down {his/her} experienced, cock-milking throat. You rock your [if(isTaur = true) " equine flanks "][if(isTaur = false) " hips "] as you roughly face-fuck the helpless [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = true) " Demonic She-male "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = true) " Succubus "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = false) " Incubus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = false) " Demonic Cunt-boy "] and use your grip on {his/her} horns to slide the infernal monster's head back and forth, forcefully dragging the dick-sucking circle of {his/her} lips up and down the length of your prick.");
			outputText("\n\nBefore long the Demon begins to suck in earnest, no doubt finding the current situation entirely familiar, {his/her} throat muscles begin to contract around your member as though trying to swallow you whole! Meanwhile the creature's inhumanly long tongue snakes around {his/her} meaty mouthful, pumping away seemingly of its own accord.");
			outputText("\n\nYou thrust and grunt as the obscene slurping of your lewd throat-fucking fills the air, your bound victim bucking beneath you, gulping your cock while simultaneously gripping the base with the dexterous coils of {his/her} tongue.");
			outputText("\n\nThe pace of your humping becomes more frantic as the stimulation grows more intense, mashing the Demon's face into your [if(isGoo = true) " gooy "][if{hasFur = true} " fuzzy "][if(isTaur = true) " underbelly, "][if(isTaur = false) " pelvis, "] until, finally, you hilt yourself in {his/her} hot, wet mouth and gasp as you [if(cumNormal = true) " squirt your load directly down the beast's waiting throat. "][if(cumMedium = true) " gush a massive load into the beast's waiting throat. "][if(cumHigh = true) " shoot seemingly endless jets of sticky cum directly down the beast's waiting throat, which {he/she} gulps down noisily. "][if(cumVeryHigh = true) " blast so much cum into the beast that {his/her} cheeks balloon comically and little jets of pearlescent spooge shoot out of {his/her} nose as {he/she} struggles to keep up with swallowing your mighty load. "][if(cumExtreme = true) " gush a vast flood of cum directly down the beast's waiting throat, and the look on the Demon's face is priceless as {he/she} realises that the torrential flood of jizz isn't letting up. As {he/she} struggles to keep up with swallowing your titanic load {his/her} cheeks balloon out, streams of cum spurt out of {his/her} nose and around your shaft, and {his/her} stomach begins to swell, eventually reaching the size of a beach-ball! "]");
			outputText("\n\nFinally, you pull your cock from {his/her} silken sheath [if(cocks > 1) ", as your other cock[if(cocks > 2) "s "] splatter[if(cocks = 2) "s "] cum onto the ground, "] and finish the last of your orgasm over the [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus’s "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = true) " Demonic She-male’s "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = true) " Succubus’s "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus’s "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = false) " Incubus’s "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = false) " Demonic Cunt-boy’s "] face, as {he/she} gasps for long-denied air. "]");
			outputText("\n\n[if(cockSmallest > 65) " You realise, with some disappointment, that there's no way you can fit [if(cocks > 2) " any of your [multiCockDescriptLight()] "][if(cocks = 2) " either of your [multiCockDescriptLight()] "][if(cocks = 1) " your [cock] "] in the Demon's mouth. Not to be defeated so easily you bark at the hellish monster to put {his/her} tongue to good use.");
			outputText("\n\nImmediately, the long, slick rope of the beast's tongue slithers between {his/her} lips to [if(cocks = 1) " encircle your hot cock , slipping and sliding across the throbbing surface, "][if(cocks > 1) " entwine {him/her}self around the throbbing poles of your dicks, writhing across them, "] as the monster's lips continue to massage your [cockHeadBiggest].");
			outputText("\n\nThe wriggling tip of the infernal organ dances [if(cocks = 1) " up and down your meaty pillar of flesh while the rest of it loops around your shaft and pulls tight, firmly gripping  your massive member even as {his/her} coils slide along your phallic length. "][if(cocks > 1) " all about your meaty pillars of flesh while the rest of it loops around your shafts and pulls tight, firmly gripping  your massive members even as {his/her} coils slide along your phallic lengths. "][if(isTaur = true) " You rest back on your haunches "][if(isTaur = false) " You lean back "] and relax as the captive demon services your [multiCockDescriptLight()] when the creature's tongue-tip rears back like a striking serpent before plunging into your piss-slit, drawing a sharp intake of breath from you.");
			outputText("\n\nA [if(isTaur = true) “ whinney “][if(isTaur = false) “ ragged sigh “] escapes your lips as you savour the sensation of the slippery tongue-lasso gliding back and forth along the length of your mighty, rock-solid prick[if(cocks > 1) “s “]. The length of flesh writhing within your cum-vein thrashes and undulates, stimulating you from within even as the ropey coils pleasure you without.");
			outputText("\n\nYou groan as the squirming tendril worms {his/her} way down your urethra, the pleasure mounts and mounts until finally, with a body-wracking shudder you [if(cumNormal = true) " squirt your load over the beast's upturned face. "][if(cumMedium = true) " gush a massive load over the beast's upturned face. "][if(cumHigh = true) " shoot seemingly endless jets of sticky cum directly all over the beast's upturned face, while {he/she} slurps down as much as {he/she} can noisily. “][if(cumVeryHigh = true) " blast so much cum all over the beast that it's soon completely coated from the chest up in spooge as {he/she} struggles to swallow as much as {he/she} can of your mighty load. "][if(cumExtreme = true) " gush a vast flood of cum all over the beast's upturned face. The Demon coughs and splutters as {he/she} struggles in vain to keep up with swallowing your titanic load until at last {he/she}'s left gasping in a big, sticky pool of jizz, trying to blink hot wads of spunk from {his/her} eyes. "] "] "]");
			outputText("\n\n[if(hasPenis = false) " [if(isTuar = true) " You position your hindquarters over the Demon's face and lower your flanks until {his/her} mouth is smooshed into your [if(hsaVagina = true " hot quim. "][if(hasVagina = false) " [butthole]. "] "][if(isGoo = true) " You ooze onto the Demon, enveloping {his/her} [if(eHasBreasts = true) " voluptuous bosom "][if(eHasBreasts = false) " chest "] [if(hasVagina = true) " and smooshing {his/her} mouth into your slimy quim. "][if(hasVagina = false) ", then turn around and smoosh {his/her} mouth into your [butthole]. "] "][if(isNaga = true) " You wrap yourself around the Demon, leaning forward to smoosh {his/her} mouth into your [if(hasVagia = true) " hot quim. "][if(hasVagina = false) " [butthole] "] "][if(isTaur = false {and} isGoo = false {and} isNaga = false) " You straddle the Demon's head and kneel down, smooshing {his/her} mouth into your [if(hsaVagina = true " hot quim. "][if(hasVagina = false) " [butthole]. "] "]");
			outputText("\n\nTasting [if(hasVagina = true) " pussy "][if(hasVagina = false) " your juicy rump "] on {his/her} lips the beast instinctively begins to lap at your [if(hasVagina = true) " [vagina] "][if(hasVagina = false) " [butt] "], the Demon licks and slurps, massaging your [if(hasVagina = true) " labia "][if(hasVagina = false) " ring-piece "] with {his/her} lips while slipping {his/her} tongue into your [if(hasVagina = true) " rapidly dampening slit "][if(hasVagina = false) " palpitating hole "].");
			outputText("\n\nYou moan and grind down as the probing appendage burrows deep inside you, and soon your [if(hasVagina = true) " pussy is [if(vaginalWetness = low) " dewy "][if(vaginalWetness = medium) " wet "][if(vaginalWetness = high) " gushing "] with fem-cum and "][if(hasVagina = false) " butthole is slathered in "] demonic saliva. At your urging the [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = true) " Demonic She-male "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = true) " Succubus "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = false) " Incubus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = false) " Demonic Cunt-boy "] lets out more and more of {his/her} great, slick rope of a tongue, first doubling back on {him/her}self within the silken innards of your [if(hasVagina = true) " [vagina] "][if(hasVagina = false) " ass "], then wriggling {his/her} tip [if(hasVagina = true) " out of your lower lips to begin tracing circles around your [clit]. "][if(hasVagina = false) " far inside your colon, stimulating and filling the deepest reaches your hole. "]");
			outputText("\n\nYou toss back your head, back arched and groan in pleasure at the sensation of the slippery coils twisting and thrashing within you as the teasing tip [if(hasVagina = true) " remorselessly flickers across your throbbing joy-buzzer. "][if(hasVagina = false) " whips around, remorselessly invading your deepest recesses. "] [if(isTaur = true) " Whinnying softly, your flanks tremble "][if(isGoo = true) " You gasp and squish your [if(hasVagina = true) " groin "][if(hasVagina = false) " ass "] into the creature's face so forcefully that you almost push {his/her} whole head into your gooie flesh "][if(isNaga = true) " You groan and involuntarily begin to tighten your coils, only realising when the beast ceases {his/her} oral ministrations, and gasps out <i>"...crushing...ribs...hhhrrggg..."</i> Blushing slightly, you relax your constricting grip a little and sigh "][if(isDrider = true) " You gasp and your legs tremble, setting two pairs of knees on either side of you knocking together "][if(isTaur = false {and} isGoo = false {and} isNaga = false {and} isDrider = false) " You press your thighs to the sides of the beast's head, gasping and groaning "] as the stimulation of your [if(hasVagina = true) " hot, slick wetness "][if(hasVagina = false) " quivering guts "] mounts.");
			outputText("\n\nYour helpless demonic captive undulates the fleshy ribbon of tongue buried within your intimate folds, corkscrewing {his/her} whorls and loops even as the tip ferociously molests your [if(hasVagina = true) " clit. "][if(hasVagina = false) " innards. "]");
			outputText("\n\nThe stimulation builds into an overwhelming crescendo causing your [if(hasVagina = true) " cunt "][if(hasVagina = false) " asshole "] to spasm with your climax, [if(hasVagina = true) " [if(vaginalWetness = low) " clamping down hard on the questing tongue as your orgasm washes over you. "][if(vaginalWetness = medium) " spurting girl jizz into the Demon's face as you clamp down hard on the questing tongue while your orgasm washes over you. "][if(vaginalWetness = high) " freely drenching the Demon's face with girl jizz  as you clamp down hard on the questing tongue while your orgasm washes over you. "] "][if(hasVagina = false) " pulsating and convulsing around the questing tongue with your ass-gasm. "] You squeal in pleasure as you ride out the throes of your climax, rocking your [if(isTaur = true) " flanks "][is(isTaur = false) " hips "] and tossing back your head, you release an orgasmic cry. "]");
			outputText("\n\n[if(hasPenis = true) " With "][if(hasPenis = false) " The beast's inhumanly long tongue slides out of you and, with "] a satisfied sigh, you climb off your demonic victim.");
			outputText("\n\nThe frustrated [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = true) " Demonic She-male "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = true) " Succubus "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = false) " Incubus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = false) " Demonic Cunt-boy "] [if(hasPenis = true) ", {his/her} face still [if(cumNormal = true) " streaked "][if(cumMedium = true) " splattered "][if(cumHigh = true) " soaked "][if(cumVeryHigh = true) " covered "][if(cumExtreme = true) " drenched "] with pearlescent spunk and "][if(hasPenis = false {and} hasVagina = true) ", {his/her} face still smeared with your cunt slime and "] {his/her} hands still bound behind {his/her} back, is desperately trying to masturbate as best {he/she} can.");
			outputText("\n\n[if(ehasPenis = true {and} ehasVagina = true) " The demonic monster's well-used tongue wraps around {his/her} throbbing cock even as {his/her} tail plunges again and again into {his/her} soaking snatch. "][if(ehasPenis = true {and} ehasVagina = false) " The demonic monster's well-used tongue wraps around {his/her} throbbing cock even as {his/her} tail plunges again and again into {his/her} puckered asshole. "][if(ehasPenis = false) "  The demonic monster's well-used tongue dives into {his/her} soaking snatch even as {his/her} tail plunges again and again into {his/her} puckered asshole. "]");
			outputText("\n\n[if(corruption < 40) " The lascivious display raises a twinge of guilt over succumbing to your base urges with a Demon, "][if (corruption => 40) " Tempting as it may be to engage with the lascivious display for round two, you have other matters to attend to, "] so you dress quickly and leave the Demon work out {his/her} frustrations on {his/her} own; the wet, urgent sounds of energetic self-abuse following you as you head off.");
			*/
			player.orgasm();
			dynStats("cor", 1);
			getGame().combat.cleanupAfterCombat();
		}
		
		private function killTheSoldier():void {
			clearOutput();
			outputText("You make quick work of the demon before hauling the now-lifeless corpse away.");
			flags[kFLAGS.DEMON_SOLDIERS_KILLED]++;
			//Additional loot!
			if (rand(8) == 0) {
				outputText("\n\nAs you're about to " + (player.isNaga() ? "slither" : "walk") + " away in satisfaction, you spot a glowing, pink crystal and a closer examination reveals it to be a lethicite. Why the demon hasn't even eaten it remains a mystery but either way, you're in luck to have recovered it before it gets eaten (and irreversibly absorbed) and you pocket it. ");
				inventory.takeItem(useables.LETHITE, getGame().combat.cleanupAfterCombat);
			}
			getGame().combat.cleanupAfterCombat();
		}
		
		public function defeatedBySoldier(hpVictory:Boolean):void {
			clearOutput();
			outputText("(Placeholder) You have lost to the demon and thus the demon has " + monster.mf("his", "her") + " way with you, leaving you abused.");
			//Demon with dick
			/*
Demon victory rape 1 (Incubus/Omnibus/She-male)

Lying prostrate at the Demon Soldier's feet, you are barely even aware of the [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = true) " Demonic She-male "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = false) " Incubus "] stripping off your [Armour]. {He/She} It takes the opportunity to run {his/her} hands across your helpless body, murmuring to {him/her}self; "Very nice, I can certainly work with this..."

Grabbing hold of your [if(isTaur = true) " hind-quarters "][if(isNaga = true) " tail "][if(isNaga = false) {and} if(isTaur = false) " hips "], the Demon yanks your ass into the air. Pushing {his/her} face [if(isNaga = true) " into "][if(isNaga = false) " between "] your [if(hasVagina = true) " [if(isNaga = true) " groin "][if(isNaga = false) " thighs "], the [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = true) " Demonic She-male "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = false) " Incubus "] presses {his/her} mouth into your [vagina] "][if(hasVagina = false) "[if(isNaga = true) " serpentine groin "][if(isNaga = false) " butt-cheeks "], the [Incubus][Omnibus] seals {his/her} lips over your [butthole] "] and snakes {his/her} demonic tongue inside you. You squirm at the sensation of the inhumanly long, slippery tendril of flesh probing the innermost recesses of your [vagOrAss], and soon your [if(hasVagina = true) " [vaginaDescript(0)] is dripping with a combination of demonic saliva and your own lubrication. "][if(hasVagina = false) " [assholeDescript()] is sopping with demonic saliva. "]


The relentless stimulation of the deepest, most intimate folds of your internal reaches has you biting your lower lip to keep yourself from crying out. Just as the tonguing really gets going, the Demon kneels upright, causing you to shudder as inch after inch of infernal tongue is whipped out of your wet hole. <i>"That seems to be enough, I think."</i> Says the corrupted beast.

All you can do is lie there and take it as you feel your demonic assailant shift {his/her} position and press the tip of {his/her} throbbing demon-cock to your [if(hasVagina = true) " well-prepared pussy lips, "][if(hasVagina = false) " spit-lubed sphincter, "] pause for a brief moment, then lunge forward to ram {his/her} entire length into you, launching into a brutal slam-fucking. Both you and the [Incubus][Omnibus] gasp and grunt as the creature pounds remorselessly at your [vagOrAss]. The rapid, drumbeat slapping of [if(isGoo = true) " flesh-on-slime "][if(isGoo = false) " flesh-on-flesh "] is overlaid with the wet, squelching of the Demon Soldier mercilessly punishing your hole.

Your eyes roll up into your head as the Demon's pelvis wallops into your [if(isNaga = true) " pubic mound "][if(isNaga = false) " buttocks "] over and over again with such force that you are actually pushed along the ground, groaning in pain and pleasure at the frenzied [if(hasVagina = true) " raping "][if(hasVagina = false) " ass-raping "] you're receiving.
[if(hasVagina = true {and} hasCock = false) " The Demon Soldier reaches underneath you to strum {his/her} dexterous fingers against your [clit], drawing an involuntary squeal from you. "]
[if(hasVagina = false {and} cocks = 1) " The Demon Soldier reaches underneath you to wrap {his/her} fingers tightly around your [cock] and begins to pump hard. "]
[if(hasVagina = false {and} cocks = 2) " The Demon Soldier reaches underneath you and begins pumping hard at [eachCock], alternating between them. "]
[if(hasVagina = false {and} cocks > 2) " The Demon Soldier reaches underneath you and entwines {his/her} fingers in amongst your pulsating cocks, teasing and stimulating them. "]
[if(hasVagina = true {and} hasCock = true) " The Demon Soldier reaches underneath you and alternates between rubbing at your [clit], and pumping {his/her} clasped fist along [eachCock], making you cry out involuntarily. "]
The tempo of the hellish beast's pistoning becomes more erratic, and spits and spurts of demonic pre-cum spray out around the creature's infernal cock.

"Aaahhhnnn... yeeesss, cum for me... unf... CUM FOR ME, FUCKSLUT!! AAAAHHHHH!!!!" The Demon shrieks, {his/her} tongue lolling from {his/her} mouth as {his/her} orgasm comes thundering up. The [if(hasVagina = true {and/or} hasCock = true) " constant manhandling of your genitalia reaches fever pitch, as the [Incubus's][Omnibus's] skilful manipulation combined with the "] vigorous power fucking you're taking has you very close to cumming, yourself.

You feel the Demon's infernal prick twitching and spasming within you, finally gushing a torrent of hellish sperm inside your [if(hasVagina = true {and} isPregnant = true) " womb. The Demon leans close to your ear and murmurs; <i>"That's it, let me soak the mewling spawn growing inside you with my demon spunk! If only I could get you double-pregnant!"</i> "][if(hasVagina = true {and} isPregnant = false) " womb. The Demon leans close to your ear and murmurs; <i>"Yes, take my corrupt seed into your belly. Grow fat with my spawn, brood-cow! It's all you pitiful mortals are good for!"</i> "][if(hasVagina = false {and} isButtPregnant = true) " bowels. The Demon leans close to your ear and murmurs; <i>"That's it, let me soak the mewling spawn growing inside you with my demon spunk! If only I could get you double-pregnant!"</i> "][if(hasVagina = false {and} isButtPregnant = false) " bowels. The Demon leans close to your ear and murmurs; <i>"Take it, bitch. Yeah, you like being my little fuck-toy, don't you, you cock-hungry buttslut?"</i> "]

Demonic spunk sprays out around the Infernal monster's cock as {he/she} continues thrusting into you, splattering sexual fluids all over the place, and triggering your own climax.

[if(hasVagina = true) " Your pussy contracts, pulsing around the intruding phallus, [if(isSquirter = true) " squirting a waterfall of fem-spunk onto the Demon Soldier's thighs. "][if(isSquirter = false) " spurting female sex-fluids from your cock-stuffed hole. "] "]
[if(hasCock = true {and} cumNormal = true) " Your [multiCockDescriptLight()] [if(cocks = 1) " bucks "][if(cocks > 1) " buck "] beneath you, squirting gouts of pearlescent jizm into the soil under you. "]
[if(hasCock = true {and} cumMedium = true) " Your [multiCockDescriptLight()] [if(cocks = 1) " bucks "][if(cocks > 1) " buck "] beneath you, spitting out long ropes of sticky cum into the dirt under you. "]
[if(hasCocks = true {and} cumHigh = true) " Your [multiCockDescriptLight()] [if(cocks = 1) " bucks "][if(cocks > 1) " buck "] beneath you, disgorging jets of spooge, mingling with the sex-juices already soaking the earth under you. "]
[if(hasCocks=true {and} cumVeryHigh = true) " Your [multiCockDescriptLight()] [if(cocks = 1) " bucks "][if(cocks > 1) " buck "] beneath you, pouring a flood of sperm onto the ground under you, saturating the already soaked earth with your seed. "]
[if(hasCocks = true {and} cumExtreme = true) " Your [multiCockDescriptLight()] [if(cocks = 1) " bucks "][if(cocks > 1) " buck "] beneath you, your pulsating [if(cocks = 1) " cum-vein "][if(cocks > 1) " cum-veins "] blasting a seemingly endless cascade of cum into the surrounding soil [if(hasBalls = true) " as your balls drain themselves of their own volition "], spooge gushes out of you faster than the soil can absorb it, leaving you and the Demon kneeling in a large pool of spunk. "]

[if(hasCock = false {and} hasVagina = false) " your sperm-filled anus twitches and pulses around the violating pillar of demon meat as your ass-gasm shudders through you. "]

[if(hasCocks = true {and} cumHigh = true) " Your [multiCockDescriptLight()] [if(cocks = 1) " bucks "][if(cocks > 1) " buck "] beneath you, disgorging jets of spooge, mingling with the sex-juices already soaking the earth under you. "]
[if(hasCocks=true {and} cumVeryHigh = true) " Your [multiCockDescriptLight()] [if(cocks = 1) " bucks "][if(cocks > 1
The [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = true) " Demonic She-male "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = true {and} ehasVagina = false {and} ehasBreasts = false) " Incubus "] pulls {his/her} now semi-flaccid dick from your [if(hasVagina = true) " thoroughly fucked cunt "][if(hasVagina = false) " thoroughly fucked ass "] with a loud, obscene slurp and makes an attempt to wipe {him/her}self off on you [armour].

You can just about manage a groan before you flopping onto the cum-splattered earth as infernal sperm flows freely from your ruined orifice.
<i>"well, this was an amusing enough diversion."</i> Muses the Demon Soldier, casually tossing your soiled [armourName] to the ground. <i>"However, the last time I was late back from patrol the Captain gave me two days in the barrel. Not that it wasn't fun, in its own way, but still, I'd best get going. I don't want to give him an excuse to think up something more... Creative. See you soon, I hope, heh heh heh."</i>

So saying, the Demon [if(gems = 1) " pulls a classic dick move by taking your last gem, then "][if(gems > 1) " helps {him/her}self to a handful of Gems from your pouch, then "] spreads {his/her} wings and, with a mighty heave, launches {him/her}self into the air. You raise your head just long enough to see the hell beast rise until {he/she}'s little more than a dot in the sky, then slump back into the cummy mud and finally pass out.

			//Demon with pussy
			Demon victory rape 2 (Omnibus/Succubus/Cunt-boy)

Lying prostrate at the Demon Soldier's feet, you are barely even aware of the [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = true) " Succubus "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = false) " Demonic Cunt-boy "] stripping off your [Armour]. {He/She} It takes the opportunity to run {his/her} hands across your helpless body, murmuring to {him/her}self; "Very nice, I can certainly work with this..."

[if(hasCock = true {and} cocks < 3 {and} biggest cock size < 6) " Your demonic assailant moves down to your groin, and points at [eachCock] and laughs, mockingly. <i>"Bwaahh hahahaha *snort* aahhaha... What the fuck [if(cocks = 1) " is [b]that[/b] "][if(cocks = 2) " are [b]those[/b] "] supposed to be? Come on, you might as well just chug a Succubi Draft and be done with it! Pffthahaha!!"</i> "]

[if(cocks > 2 {and} biggest cock size < 6) " Your demonic assailant moves down to your groin, and smirks at your stubby cock-cluster. <i>"Pfftt ahhahaha... So, what? you thought you could make up for lack of quality with quantity, maybe? Ha!"</i> "]

[if(hasCock = true {and} cocks < 3 {and} biggest cock size => 6 {and} < 16) " Your demonic assailant moves down to your groin, and indifferently appraises [eachCock]. <i>"Hmm, [if(cocks = 1) " this "][if(cocks = 2) " these "] will do, I suppose, but [if(cocks = 1) " it's "][if(cocks = 2) " they're "] hardly a challenge to one of [b]my[/b] abilities."</i> "]

[if(cocks > 2 {and} biggest cock size => 6 {and} < 16) " Your demonic assailant moves down to your groin, and cooly regards your cluster of dicks. <i>"Could be worse, I suppose. Still, hardly a stretch for me, so to speak."</i> "]

[if(hasCock=true {and} cocks < 3 {and} biggest cock size => 16 {and} < 30) " Your demonic assailant moves down to your groin, and quirks an eyebrow at your [multiCockDescriptLight()]. <i>"Nice, [if(cocks = 1) " this "][if(cocks = 2) " these "] will do very nicely..."</i> "]

[if(cocks > 2 {and} biggest cock size => 16 {and} < 30) " Your demonic assailant moves down to your groin, and smiles at the sight of [multiCockDescriptLight()]. <i>"Oh, a buffet? I like it!"</i> "]

[if(hasCock = true {and} cocks < 3 {and} biggest cock size => 30 {and} < 90) " Your demonic assailant moves down to your groin, and licks {his/her} lips at the sight of your [multiCockDescriptLight()]. <i>"Oooh... I think I'm going to enjoy you."</i> "]

[if(cocks > 2 {and} biggest cock size => 30 {and} < 90) " Your demonic assailant moves down to your groin, and grins from ear to ear at the sight of your [multiCockDescriptLight()]. <i>"Oh my, they all look so good. I'll have to sample each one!"</i> "]

[if(hasCock = true {and} cocks < 3 {and} biggest cock size => 90 {and} < 200) " Your demonic assailant moves down to your groin, and begins to salivate at the sight of your massive meat. <i>"Yum, yum, now [if(cocks = 1) " [b]that's[/b] a [b]real[/b] cock! "][if(cocks = 2) " [b]those[/b] are [b]real[/b] cocks!" "]</i>" "]

[if(cocks > 2 {and} biggest cock size => 90 {and} < 200) " Your demonic assailant moves down to your groin, and squeals with glee at sight of your outsized clump of fuck-sticks. <i>"Eeee... I can see you and I are going to get along [b]very[/b] well indeed! Oh my, yes!"</i> "]

[if(cocks < 3 {and} biggest cock size => 200) " Your demonic assailant moves down to your groin, eyeing up your ludicrously over-sized [if(cocks = 1) " column "][if(cocks = 2) " columns "] of phallic flesh. <i>"Holy shit! [if(cocks = 1) " That's "][if(cocks = 2) " Those are "] the biggest [if(cocks = 1) " cock "][if(cocks = 2) " cocks "] I've seen all week! Well, let no-one say I ever backed down from a challenge..."</i> "]

[if(cocks > 2 {and} biggest cock size => 200) " Your demonic assailant moves down to your groin, mouth agape at the sight of your thicket of mega-cocks. <i>"Fucking hell! Someone's been having some fun with Incubus Drafts, eh? How the ever-loving fuckballs did you even fit these in your [armour], anyway?"</i> "]

[if(hasVagina = true {and} hasCock = false) " Your demonic assailant moves down your body, leaning in closer to your [vaginaDescript(0)], cooing <i>"Let's see what we have here: [if(vaginal Looseness =< 5) " "Oooh, what a cute, tight little snatch," "][if(vaginal Looseness => 15) " "Mmm, now here's a slut's cunt if ever I saw one," "] I'll bet it tastes so sweet..."</i> "]

[if(hasVagina = false {and} hasCock = false) " Your demonic assailant moves down to your groin. Finding only a smooth patch, a puzzled look passes across {his/her} face before resolving into a sly grin: <i>"A challenge eh? I love a challenge! Let's see here..."</i> "]

[if(isHerm = true) " [if(hasBalls = true) " Shifting your [ballsDescriptLight()] to one side, "][if(hasBalls = false) " Sliding {his/her} hands down to your [vaginaDescript(0)] "] the infernal beast continues: <i>"Oooh, and what have we here? looks like someone has a little something extra..."</i> "]

[if(hasCock = true) " The Demon [if(cock biggest width < 3) " slips {his/her} mouth over the end of your [cock biggest], "][if(cock biggest width => 3 {and} =< 4.5) " stretches {his/her} mouth over the end of your [cock biggest], "][if(cock biggest width > 4.5) " places a series of sloppy kisses long the length of your [cock biggest] to suckle at your piss-slit "] and swirls {his/her} tongue around your [cockHead biggest]. The stimulation causes you to sharply exhale involuntarily, and your [multiCockDescriptLight()] to begin to swell. The [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = true) " Succubus "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = false) " Demonic Cunt-boy "] withdraws, releasing your cock from suction, a glistening spider-web of saliva linking the [cockHead biggest] of your [cock biggest] with the infernal monster's lips. "]

[if(hasVagina = true {and} hasCock = false) " The Demon traces around the edges of your pussy lips with the tip of {his/her} infernal tongue, before flickering the end of the slimy appendage across your [clit], making you gasp in pleasure as your sex fluids begin to flow freely. Strands of pussy juice and demon spit stretch between your moistened sex-hole and the Demon's lips as {he/she} withdraws from the tonguing. "]

[if(hasVagina = false {and} hasCock = false) " The Demon [if(isNaga = false) " pushes {his/her} face into your [butt], and"] presses {his/her} lips to your [butthole]. You feel a pressure at your sphincter, and the beast's inhuman tongue burrows its way into your bowels. The sensation of the slimy appendage questing into the inner folds of your rectum forces a moan from your lips. The hellish creature withdraws with an audible slurp, yanking over a foot of tongue from your ass, and making you gasp, sharply. "]

<i>"Mmmmm, delicious."</i> {He/She} hisses <i>"Now, let's put that pretty little mouth of yours to good use."</i>

[if(isTaur = true {or} Player Character height > 7'6") " On all fours, the [Omnibus][Succubus] slinks up to your head, and, with "][if(isTaur = false {and} Player Character height =< 7'6") " With "] a smooth swivel, [if(isTaur = false) {and} Player Character height =< 7'6") " the [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = true) " Succubus "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = false) " Demonic Cunt-boy "] "] straddles your face.

Your mouth is smooshed into the Demonic monster's drooling cock-socket [if(eHasBalls = true) ", {his/her} plump balls resting on your chin "] as {he/she} begins to rock {his/her} hips back and forth, rubbing {his/her} slippery snatch across your lips. <i>"Come on, mortal; get licking. Don't pretend you don't want to."</i> The irresistibly sweet, spicy scent of infernal cunt slime fills your nostrils, inflaming your lusts, and soon [if(has Demonic Tongue = true) " your own demonic tongue is delving and swirling through the hot, slick depths of the Demon's fuck-hole. "][if(has Demonic Tongue = false) " you're lapping hungrily at the Demon's fuck-hole, probing at the hot, slick interior. "]

The Demon clamps {his/her} thighs to the sides of your head and squeals. <i>"Eeeee... Now you're getting the idea! Ooooh, work the clit! Work the clit!"</i>

Responding to the hell-beast's urgings almost against your own will [if(has Demonic Tongue = true) " the tip of your infernal tongue doubles back on {him/her}self, slipping out from between the Demon's wet cunt lips to begin circling her throbbing bitch-button. "][if(has Demonic Tongue = false) " you begin alternating between ramming your tongue as deep as you can into {his/her} gooeyie snatch, and circling {his/her} throbbing bitch-button. "]

As demonic fem-juices begin to dribble across your [face] [if(ehasCock = true) " and hot pre-cum starts spitting onto your [chest] from the end of {his/her} pulsating cock, "] the [[if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = true) " Succubus "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = false) " Demonic Cunt-boy "] grinds {his/her} hips down in response to your efforts and groans in pleasure.

<i>"Hhhhnnnnyyyyyeeeessssss... Good, nnngooood, hhhaaaahhh... Now... I want to... unf... taste you..."</i>

[if(isTaur = true {and/or} Player Character height > 7'6") " Your infernal attacker lashes out {his/her} tongue, [if(hasCock = true) " [if(cocks > 1) " snaking "][if(cocks = 1) " wrapping "] it around your [multiCockDescriptLight()] [if(cocks = 1) " a few times "][if(hasVagina = false " . "] "]
[if(hasVagina = true) " [if(hasCock = true) " , and  "]plunging the end down into your [vaginaDescript(0)], wriggling {his/her} way into your [if(vaginalWetness = low {and} isGoo = false) " moist "][if(vaginalWetness = medium {and} isGoo = false) " slippery "][if(vaginalWetness = high {and} isGoo = false) " sopping "][if(isGoo = true) " liquid "] depths.
[if(hasVagina = false {and} hasCock = false) " plunging the end into your butt-hole and corkscrewing the soft, wet tendril deep, deep inside your colon."] "]

[if(isTaur = false {and} Player Character height =< 7'6") " Your infernal attacker leans forward,
[if(hasCock = true) " [if(cock biggest width =< 4.5 " [if(cock biggest width < 3) " engulfing the end of your [cock biggest] in {his/her} hot, wet mouth "][if(cock biggest width => 3 {and} =< 4.5) " forcing the end of your [cock biggest] past {his/her} stretched jaw "] and easily swallowing down [if(cock biggest length > 14) " over a foot of your throbbing length. "][if(cock biggest length =< 14) " your entire throbbing length down to the [sheath], burying {his/her} nose in your [if(hasBalls = true) " [sack]. "][if(hasBalls = false {and} hasVagina = true) " [vagina] "][if(hasBalls = false {and} hasVagina = false) " taint. "] "][if(cock biggest width > 4.5) " messily licks {his/her} way along the length of your [cock biggest] to encircle the [cockHead biggest] with {his/her} tongue. "][if(cocks > 1 {and} < 4) " [if(cocks = 2) " Your other cock rubs "][if(cocks = 3) " Both of your other cocks rub "] up against the Demon's [if(cocks > 2) " cheeks "][if(cocks = 2) " cheek "]
as {he/she} bobs {his/her} head along your dick. "][if(cocks > 3) " The Demon plunges face-first into your [mutiCockDescriptLight()] as {he/she} [if(cock biggest width =< 4.5) " bobs {his/her} head "][if(cock biggest width > 4.5) " slides {his/her} tongue-lasso "] along your the length of your dick. "]

[if(hasVagina = true) " The monster slips {his/her} tongue [if(hasPenis = true) "[if(cock biggest width =< 4.5) " from {his/her} cock-stuffed mouth, circling your [sheath] "][if(cock biggest width > 4.5) " further and further from {his/her} mouth, causing the noose around your dick to spin pleasurably"] "]
[if(hasBalls = true) " and surging around your [sack], before corkscrewing "][if(hasBalls = false) " before slithering "] into your [vaginaDescript(0)]. The rope of demon-flesh wriggles its way into your [if(vaginalWetness = low {and} isGoo = false) " damp "][if(vaginalWetness = medium {and} isGoo = false) " wet "][if(vaginalWetness = high {and} isGoo = false) " gushing "][if(isGoo = true) " slimy "] pussy. "]

[if(hasVagina = false {and} hasCock = false) " the monster slips {his/her} tongue out, jamming the end deep into your ass-hole and writhing its way right up inside you. "] "]

The Hellish Beast's frenetic oral stimulation has you moaning into the girl-jizz soaked folds of {his/her} cunt, driving you wild and sending your tongue swirling faster and faster through {his/her} sodden recesses. In turn this feeds the creature's sexual frenzy, causing {him/her} to [if(cocks > 1) " reach out
[if(cocks > 3) " and grab hold of two of your other cocks "][if(cocks = 3) " and grab hold of both of your other cocks "][if(cocks = 2) " with both {his/her} hands to grasp your [cock smallest] "] and begins to pump hard and fast. "][if(cocks = 1) " [if(isNaga = true) " reach out to your groin, "][if(isNaga = false) " shove {his/her} hands between your legs, "][if(hasBalls = true) " caressing your [balls] with one hand whilst, with the other, "][if(hasVagina = true) " {he/she} thrusts {his/her} fingers past your pussy lips, wiggling and wriggling inside you alongside {his/her} tongue. "][if(hasVagina = false) " [if(isNaga = true) " {he/she} runs {his/her} hands over your serpentine hips, before "][if(isNaga = false) " {he/she} gropes roughly at your buttocks, "] poking several fingers into your [butthole], searching out your prostate "] "][if(hasPenis = false) " [if(isNaga = true) " reach out to your groin, "][if(isNaga = false) " shove {his/her} hands between your legs, "][if(hasVagina = true) " and thrust {his/her} fingers past your pussy lips, wiggling and wriggling inside you along side {his/her} tongue. "][if(hasVagina = false) " [if(isNaga = true) " {he/she} runs {his/her} hands over your serpentine hips, before "][if(isNaga = false) " {he/she} gropes roughly at your buttocks, "] poking several fingers into your [butthole], searching out your prostate. "] "]

You lie beneath the Demon Soldier, sucking, licking, bucking and writhing. Tongue whirling and twirling as the [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = true) " Succubus "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = false) " Demonic Cunt-boy "] gropes and suckles at your flesh. The overwhelming musk of the abomination's sloppy fuck-hole and the mounting pleasure drive you rapidly towards your imminent orgasm. Judging by the way the Demon's soaking cunt is splashing infernal sex-fluids across your face the [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = true) " Succubus "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = false) " Demonic Cunt-boy "] must be nearing {his/her} own climax.

The Demon moans in {his/her} orgasm, {his/her} tongue [if(hasPenis = true) " ripples around your [if(cocks > 1) " cocks, "][if(cocks = 1) " cock, "] "][if(isHerm = true) " and "][if(hasVagina = true) " quivers all along the length buried in your snatch, "][if(hasVagina = false {and} hasPenis = false) " quivers all along the length buried in your ass, "][if(isTaur = false {and} Player Character height =< 7'6") " [if(hasPenis = true {and} cock biggest width =< 4.5) " {his/her} throat vibrating around your phallic meat, "][if(hasVagina = true {and} hasPenis = false) " as {he/she} murrmurs incoherant groans of ecstasy into your pussy, "][if(hasVagina = false {and} hasPenis = false) " momentarily breaking the seal of {his/her} lips over your ass-hole to utter incoherent groans of ecstasy, "] "] building to a shuddering peak. Your hellish attacker's cooch spasms around your tongue, and a cascade of femme-jizz blasts you in the [face] [if(ehasCock = true) ", as {his/her} bulging, bouncing demon-prick disgorging an almost continuous stream of pre-cum, giving way to a series of powerful jets of infernal sperm"].

The Demon Soldier jerks back {his/her} head, [if(hasPenis = true) " [if(isTaur = true {and/or} Player Character height > 7'6" {and/or} cock biggest width> 4.5) " and the long ribbon of demonic tongue whips [if(cocks = 1) " around your cock "][if(cocks > 1) " between your cocks "] “][if(isTaur = false {and} Player Character height =< 7'6" {and} cock biggest width =< 4.5) " your dick slides from the Demon's throat, [if(cocks =< 2) " and the long ribbon of demonic tongue whips [if(cocks = 2) " around the base of your other cock "][if(cocks > 2) " between your other cocks "] "][if(hasVagina = true) " slipping from your sodden cunt as it retracts into the hell-beast's mouth "], "][if(hasVagina = true {and} cocks = false) " {his/her} tongue whips from your soaking hole, "][if(hasVagina = False {and} hasPenis = false) " {his/her} tongue whips from your spit-slimed butt-hole, "] as the sex-crazed monster shrieks with climactic release.

The sudden sensation of the demonic tongue [if(hasPenis = true) " flashing around your cock[if(cocks > 1) "s "] "][if(hasPenis = false) " being snatched from your hole "] drives you past your limit, triggering your orgasm. Your [if(hasPenis = true) " [multiCockDescriptLight()][if(cocks > 1) " quiver and flail "][if(cocks = 1) " quivers and flails "][if(cumNormal) " spitting out long strands of sticky cum "][if(cumMedium) " squirting gouts of pearlescent jizm "][if(cumHigh) " disgorging great, twirling ropes of spooge "][if(cumVeryHigh) " fountaining a flood of sperm high "][if(cumExtreme) " blasting a seemingly endless cascade of cum "] into the air [if(hasBalls = true) " as your balls drain themselves of their own volition "], "][if(hasVagina = true) " your[if(isSquirter = true) " gushing cunt flutters as it erupts with a waterfall of girl-cum "][if(isSquirter = false) " soaking pussy flutters as it spurts and splatters girl-cum "] "][if(hasVagina = false {and} hasPenis = false) " quivering anus winks and flutters "] while your orgasm stampedes through you.

Almost unnoticed as you ride out the last of your climax, the [if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = true) " Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = true) " Succubus "][if(ehasPenis = true {and} ehasVagina = true {and} ehasBreasts = false) " Masculine Omnibus "][if(ehasPenis = false {and} ehasVagina = true {and} ehasBreasts = false) " Demonic Cunt-boy "] staggers to {his/her} feet as {his/her} own thunderous apex winds down and tries to wipe the sticky, sex-fluids smeared over {his/her} skin onto your [armour].

<i>"well, this was an amusing enough diversion."</i> Muses the Demon Soldier, casually tossing your soiled [armourName] to the ground. <i>"However, the last time I was late back from patrol the Captain gave me two days in the barrel. Not that it wasn't fun, in its own way, but still, I'd best get going. I don't want to give him an excuse to think up something more... Creative. See you soon, I hope, heh heh heh."</i>

So saying, the Demon [if(gems=1) "pulls a classic dick move by taking your last gem, then"][if(gems>1) "helps {him/her}self to a handful of Gems from your pouch, then"] spreads {his/her} wings and, with a mighty heave, launches {him/her}self into the air. You raise your head just long enough to see the hell beast rise until {he/she}'s little more than a dot in the sky, then slump back into the dirt and finally pass out.


			 */
			player.orgasm();
			getGame().combat.cleanupAfterCombat();
		}
	}

}