#!/bin/sh

# This script preserves the HTML reports generated by flexunit, as they are lost once the build VM is terminated.
# This should help developers fix build faliures related to unit tests.

# pack all files into a tar file and compress it, then encode it in base64, to make it terminal friendly.
tar cz target/report/html/ | base64

