#!/bin/sh

# This script preserves the HTML reports generated by flexunit, as they are lost once the build VM is terminated.
# This should help developers fix build faliures related to unit tests.

REPORT_DIR="target/report"
HTML_DIR="$REPORT_DIR/html"

# Check that the script is executed from the root of the project 
if [ ! -d "$REPORT_DIR" ]; then
	echo "Could not find report directory, was the script executed in project root?"
	exit 1
fi

# Check that the html output folder is present
if [ ! -d "$HTML_DIR" ]; then
	echo "Could not find html directory, were the unit tests run (compile error)?"
	exit 2
fi

# pack all files into a tar file and compress it, then encode it in base64, to make it terminal friendly.
tar cz target/report/html/ | base64

